#logging:
#  level:
#    org.springframework.security: trace
spring:
  security:
    user:
      name: "user"
      password: "pw"
      roles:
        - "USER"
        - "READ"
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080
        client:
          login-client:
            registration:
              client-id: "login-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8082/login/oauth2/code/login-client"
                - "http://127.0.0.1:8082/authorized"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true